#!/usr/bin/env bash
# print domains and subdomains

print_domain_subdomain () {
    dig +short "$1.$2" | awk -v subdomain="$1" ' NR==1 { print "The subdomain " subdomain " is a A record and points to " $0 }'
}

if [ "$#" -eq 2 ]
then
    print_domain_subdomain "$2" "$1"
else
    print_domain_subdomain "www" "$1"
    print_domain_subdomain "lb-01" "$1"
    print_domain_subdomain "web-01" "$1"
    print_domain_subdomain "web-02" "$1"
fi
