#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.

# Update package lists
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
# Frontend configuration
frontend godspower-frontend
    bind *:80
    mode http
    default_backend godspower-backend

# Backend configuration
backend godspower-backend
    balance roundrobin
    server 63210-web-01 54.160.97.148:80 check
    server 63210-web-02 52.87.235.176:80 check
EOF

# Enable HAProxy service
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
